apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: davmaio-minio
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: davmaio-minio
    spec:
      osType: linux
      containers:
      - name: davmaio-minio
        securityContext:
            runAsUser: 1001
        image: bitnami/minio:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MINIO_ROOT_USER
            value: davma-minio
          - name: MINIO_ROOT_PASSWORD
            value: davma-minio@
        resources:
          cpu:
            required: 200m
          memory:
            required: 256Mi
        ports:
          - name: http
            value: 9001
            containerPort: 9001
            type: TCP

        