apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: davmaio-minio
  annotations:
    version: 0.0.1
    description: "MinIO is a High Performance Object Storage released under GNU Affero General Public License v3.0. It is API compatible with Amazon S3 cloud storage service"
spec:
  components:
    - componentName: davmaio-minio
      traits:
        - trait:
            apiVersion: core.napptive.com/v1alpha1
            kind: Ingress
            metadata:
              name: davmaio-minio-ingress
            spec:
              name: davmaio-minio
              protocol: HTTP
              port: 9001
              path: /
              rewritePath: /
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            metadata:
              name: example-appconfig-trait
            spec:
              replicaCount: 1
      scopes:
        - scopeRef:
            apiVersion: core.oam.dev/v1alpha2
            kind: HealthScope
            name: davmaio-minio-health